### ISSUE TITLE
Widescreen Webcam?

### ISSUE THREAD

**Issue by franzvezuli** [michaelsboost/CamDesk#1]
Hello,

I have a 720p Logitech webcam that supports Widescreen, but I only see 4:3 on CamDesk. Changing the resolution just stretches it, but doesn't change the aspect ratio.

Are there plans in support widescreen webcams? Thanks!

**Comment by michaelsboost** [comment]
With CamDesk being free and open source I haven't decided to add that functionality to the non-windows releases. Due to the fact that I still have to make a living. 
I actually considered doing a Kickstarter to add additional functionality to CamDesk along with Android release but I just haven't had the time and I don't see it really panning out the way I'd hope. 
On Nov 8, 2015 11:44 AM, franzvezuli notifications@github.com wrote:Hello,

I have a 720p Logitech webcam that supports Widescreen, but I only see 4:3 on CamDesk. Changing the resolution just stretches it, but doesn't change the aspect ratio.

Are there plans in support widescreen webcams? Thanks!

**Comment by franzvezuli** [comment]
Fair enough! Thanks for the feedback. If you ever get your kick-starter up and running, I can help spread the word. We were using this for a streaming solution at my gaming site/channel.

**Comment by michaelsboost** [comment]
Muchas Gracias hermano.
Thanks man will do.
On Nov 8, 2015 1:30 PM, franzvezuli notifications@github.com wrote:Fair enough! Thanks for the feedback. If you ever get your kick-starter up and running, I can help spread the word. We were using this for a streaming solution at my gaming site/channel.
