### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by joaoherberto** [michaelsboost/CamDesk#4]
That is a shame, I relly like this app...

**Comment by michaelsboost** [comment]
I understand your concern. 

I've been developing free and open source applications for years and have contributed to many as well such as [Codemirror](http://codemirror.net/) (not because of money but because I want to make the web a better place). However, there are only 2 reasons why I am not developing CamDesk anymore. Time and Money. Currently, I am not willing to spend my time to continue development because it's not a smart decision monetarily due to the bills I have to pay. 

You see ideas are easy but actually making that idea come to reality can sometimes be a very timely process. For example, it took me 4 years developing WebDGap in my free time to make it possible for you to make Mac apps in the browser and on an Android device.

I hope you can understand why I abandoned CamDesk's development and remember that CamDesk is and will always be a free and open source application so if anyone has any ideas or implementations they want to add in they can, by all means, do so.

**Comment by michaelsboost** [comment]
Do you by any chance have a question @joaoherberto?
